version: '3.4'

services: 
  ms-sql-server:
    image: microsoft/mssql-server-linux:2017-latest
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd"
    ports: 
      - "1433:1433"
  dockertestapi:
    build: .
    environment: 
      DBServer: "ms-sql-server"
    ports: 
      - "8080:80"